### ISSUE TITLE
Polymer Error

### ISSUE THREAD

**Issue by winderine** [samolego/SimpleVillagers#21]
I added this mod to the 1.19.2 Better MC [Fabric] modpack and am now getting this error as well as red text on the Jade overlay when I hover over blocks from this mod. The blocks seem to be working properly, though. Is this something that is concerning to you?

```
07/01/2023 - 01:13:20
eu.pb4.polymer.impl.client.compat.JadeCompatibility$BlockOverride@3a795a31
java.lang.ClassCastException: class snownee.jade.addon.core.RegistryNameProvider$Mode cannot be cast to class java.lang.Boolean (snownee.jade.addon.core.RegistryNameProvider$Mode is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5e5792a0; java.lang.Boolean is in module java.base of loader 'bootstrap')
	at snownee.jade.impl.config.PluginConfig.get(PluginConfig.java:76)
	at snownee.jade.api.config.IPluginConfig.get(IPluginConfig.java:38)
	at eu.pb4.polymer.impl.client.compat.JadeCompatibility$BlockOverride.appendTooltip(JadeCompatibility.java:71)
	at snownee.jade.impl.BlockAccessorImpl._gatherComponents(BlockAccessorImpl.java:120)
	at snownee.jade.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:127)
	at snownee.jade.util.ClientPlatformProxy.onClientTick(ClientPlatformProxy.java:156)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$edh000$fabric-lifecycle-events-v1$onEndTick(class_310.java:18473)
	at net.minecraft.class_310.method_1574(class_310.java:1907)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by winderine** [comment]
Here is an example of the error. It reads 
```<Error from Polymer (Core) mod, plz report>```

![2023-07-01 01_41_02-D__Games_ATLauncher_instances_1BMC1v185_screenshots](https://github.com/samolego/SimpleVillagers/assets/52304340/042d6ebc-9916-40b9-9c40-82b6e769d47d)

**Comment by samolego** [comment]
Please report this directly to https://github.com/patbox/polymer
