### ISSUE TITLE
Incubator overflow

### ISSUE THREAD

**Issue by bugtig6351** [samolego/SimpleVillagers#8]
Hello,
I find a bug that if a hopper push villager eggs into an Incubator that all slots are full, the game will crash

log:
`
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4165)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at org.samo_lego.simplevillagers.block.entity.AbstractFarmBlockEntity.method_5438(AbstractFarmBlockEntity.java:56)
	at net.minecraft.class_2614.method_17769(class_2614.java:182)
	at java.base/java.util.stream.MatchOps$2MatchSink.accept(MatchOps.java:119)
	at java.base/java.util.Spliterators$IntArraySpliterator.tryAdvance(Spliterators.java:1085)
	at java.base/java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.allMatch(IntPipeline.java:542)
	at net.minecraft.class_2614.method_11258(class_2614.java:181)
	at net.minecraft.class_2614.method_11246(class_2614.java:149)
	at net.minecraft.class_2614.method_11243(class_2614.java:116)
	at net.minecraft.class_2614.method_31692(class_2614.java:103)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4165)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at org.samo_lego.simplevillagers.block.entity.AbstractFarmBlockEntity.method_5438(AbstractFarmBlockEntity.java:56)
	at net.minecraft.class_2614.method_17769(class_2614.java:182)
	at java.base/java.util.stream.MatchOps$2MatchSink.accept(MatchOps.java:119)
	at java.base/java.util.Spliterators$IntArraySpliterator.tryAdvance(Spliterators.java:1085)
	at java.base/java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.allMatch(IntPipeline.java:542)
	at net.minecraft.class_2614.method_11258(class_2614.java:181)
	at net.minecraft.class_2614.method_11246(class_2614.java:149)
	at net.minecraft.class_2614.method_11243(class_2614.java:116)
	at net.minecraft.class_2614.method_31692(class_2614.java:103)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.class_2614
	Block: Block{minecraft:hopper}[enabled=true,facing=down,from=up]
	Block location: World: (113,65,-50), Section: (at 1,1,14 in 7,4,-4; chunk contains blocks 112,-64,-64 to 127,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block: Block{minecraft:hopper}[enabled=true,facing=down,from=up]
	Block location: World: (113,65,-50), Section: (at 1,1,14 in 7,4,-4; chunk contains blocks 112,-64,-64 to 127,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

version:
minecraft 1.18.2
fabric-loader 0.14.6
Simple Villagers 1.2.2

**Comment by samolego** [comment]
Thanks for reporting!
